apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
spec:
  type: LoadBalancer
  selector:
    app: {{.Values.appName}}
  ports:
    - protocol: TCP
      port: {{.Values.service.data.port}}
      targetPort: {{.Values.service.data.port}}
